services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./k8s/prometheus.yml:/etc/prometheus/prometheus.yml
